#!/bin/sh -e

xgettext -o img2brl.pot -ktranslate \
--package-name=img2brl --package-version=0.1 \
--msgid-bugs-address=mlang@delysid.org ../src/img2brl.cc
for lang in de fa fr hu it
do msgmerge --quiet --update --backup=none $lang.po img2brl.pot
done
